version: '3.7'

services:
    serve:
      container_name: http-server
      restart: on-failure
      build:
        context: .
        dockerfile: Dockerfile
      command: "-root ./public"
      environment:
        - GIN_MODE=release
      volumes:
        - ./fixtures:/app/public:ro
      ports:
        - "80:80"