version: '3.7'

services:
    serve:
      restart: on-failure
      build:
        image: sundowndev/http-server:latest
        command: "--root ./public"
        networks:
        - default
        - web
      environment:
        - GIN_MODE=release
      volumes:
        - ./public:/app/public:ro
      labels:
        - 'traefik.docker.network=web'
        - 'traefik.enable=true'
        - 'traefik.domain=example.com'
        - 'traefik.basic.frontend.rule=Host:example.com'
        - 'traefik.basic.port=80'
        - 'traefik.basic.protocol=http'
        - 'traefik.frontend.headers.SSLRedirect=true'
        - 'traefik.frontend.headers.STSSeconds=315360000'
        - 'traefik.frontend.headers.browserXSSFilter=true'
        - 'traefik.frontend.headers.contentTypeNosniff=true'
        - 'traefik.frontend.headers.forceSTSHeader=true'
        - "traefik.frontend.headers.contentSecurityPolicy=default-src 'self';frame-ancestors 'self';style-src 'self';script-src 'self';img-src 'self';font-src 'self'"
        - 'traefik.frontend.headers.referrerPolicy=no-referrer'
        - 'traefik.frontend.headers.frameDeny=true'

networks:
  web:
    external: true